const CATEGORY_INTENT_SAMPLES = {
    open_jobs: [
        'open jobs',
        'show jobs',
        'available jobs open karanna',
        'mata jobs pennanna',
        'job tab eka open karanna',
        'pending jobs show karanna',
        'රැකියා පෙන්වන්න',
        'jobs balanna',
    ],
    open_history: [
        'open history',
        'show past jobs',
        'job history open karanna',
        'mata ongoing jobs pennanna',
        'past jobs balanna',
        'history tab eka open karanna',
        'ඉතිහාසය පෙන්වන්න',
        'ongoing jobs show karanna',
    ],
    open_earnings: [
        'open earnings',
        'show earnings',
        'earned tab eka open karanna',
        'mage earnings pennanna',
        'wallet eka open karanna',
        'withdraw balance pennanna',
        'ආදායම පෙන්වන්න',
        'earnings balanna',
    ],
    open_service_setup: [
        'open service setup',
        'service setup eka open karanna',
        'show my service categories',
        'service categories pennanna',
        'mata service setup balanna one',
        'සේවා සැකසුම පෙන්වන්න',
    ],
    open_chat: [
        'open chat',
        'chat eka open karanna',
        'message eka open karanna',
        'householder ekka chat karanna',
        'technician ekka chat karanna',
        'chat balanna',
    ],
    track_technician: [
        'track technician',
        'show technician location',
        'technician inne koheda',
        'mage technician balanna',
        'technician track karanna',
        'තාක්ෂණ ශිල්පියා ලුහුබඳින්න',
    ],
    make_payment: [
        'make payment',
        'digital payment karanna',
        'payment page eka open karanna',
        'job eka gewanna',
        'ගෙවීම කරන්න',
    ],
    rate_technician: [
        'rate technician',
        'give rating',
        'technician ta rating denna',
        'feedback denna',
        'තාක්ෂණ ශිල්පියා ඇගයන්න',
    ],
    accept_job: [
        'accept this job',
        'accept job',
        'job eka bara ganna',
        'mata meka accept karanna one',
        'රැකියාව භාර ගන්න',
    ],
    view_job_details: [
        'view job details',
        'job details open karanna',
        'meka details pennanna',
        'show job information',
        'රැකියා විස්තර බලන්න',
    ],
    open_report_to_electricity_board: [
        'report to electricity board',
        'select report electricity board',
        'electricity board report',
        'viduli mandalayata report karanna',
        'viduli mandalayata report karanna thoranna',
        'විදුලි මණ්ඩලයට වාර්තා කරන්න',
        'ප්‍රදේශීය විදුලි බිඳවැටීම් වාර්තා කිරීම',
    ],
    open_power_supply_issues: [
        'select power supply issues',
        'power supply issues',
        'supply problems',
        'current issues',
        'widuli sapayum getalu',
        'widuli sapayum getalu thoranna',
        'widuli sapayum getalu wetha yanna',
        'විදුලි සැපයුම් ගැටළු',
        'විදුලි සැපයුම් ගැටළු වෙත යන්න',
    ],
    open_voltage_technical_issues: [
        'select voltage technical issues',
        'voltage technical issues',
        'voltage issues',
        'voltage getalu',
        'වෝල්ටීයතා සහ තාක්ෂණික ගැටළු',
        'වෝල්ටීයතා ගැටළු',
    ],
    open_safety_related_issues: [
        'select safety related issues',
        'safety related issues',
        'safety issues',
        'arakshawa sambandha getalu',
        'ආරක්ෂාව සම්බන්ධ ගැටළු',
        'ආරක්ෂක ගැටළු',
    ],
    open_infrastructure_issues: [
        'select infrastructure issues',
        'open infrastructure issues',
        'infrastructure issues thoranna',
        'yatithala pahasukam getalu',
        'infrastructure issues',
        'යටිතල පහසුකම් ගැටළු',
        'යටිතල පහසුකම් ගැටළු තෝරන්න',
    ],
    open_monitoring_device_issues: [
        'select monitoring device issues',
        'monitoring device issues',
        'device monitoring issues',
        'adhikshana saha upanga getalu',
        'අධීක්ෂණ සහ උපකරණ ගැටළු',
        'උපාංග සම්බන්ධතා ගැටළු',
    ],
    open_activities: [
        'open activities',
        'activities balanna',
        'kriyakarakam balanna',
        'ක්‍රියාකාරකම් බලන්න',
    ],
    open_account: [
        'open account',
        'account eka open karanna',
        'ginuma open karanna',
        'ගිණුම විවෘත කරන්න',
    ],
    open_help_support: [
        'open help support',
        'help support',
        'udaw saha sahaya',
        'උදව් සහ සහාය',
    ],
    open_about_us: [
        'open about us',
        'about us',
        'api gena',
        'අප ගැන',
    ],
    go_home: [
        'go home',
        'home page',
        'dashboard',
        'මුල් පිටුවට යන්න',
    ],
    go_back: [
        'go back',
        'previous page',
        'passe yanna',
        'ආපසු යන්න',
    ],
    continue_to_location: [
        'continue to location',
        'go to location',
        'location ekata yanna',
        'location page ekata yanna',
        'set location next',
        'open location screen',
        'ස්ථානය වෙත යන්න',
        'ස්ථානය සැකසීමට යන්න',
    ],
    use_current_location: [
        'use current location',
        'current location',
        'wathman sthanaya bhawitha karanna',
        'වත්මන් ස්ථානය භාවිතා කරන්න',
    ],
    search_location: [
        'search location',
        'find location',
        'location hoyanna',
        'ස්ථානය සොයන්න',
    ],
    confirm_location_and_report_issue: [
        'confirm location and report issue',
        'report issue now',
        'sthanaya thahawuru karala report karanna',
        'ස්ථානය තහවුරු කර ගැටලුව වාර්තා කරන්න',
    ],
    confirm_location_technician: [
        'confirm technician location',
        'confirm location technician',
        'technician location confirm karanna',
        'ස්ථානය තහවුරු කරන්න',
    ],
    find_available_technicians: [
        'find available technicians',
        'find technician',
        'available technicians hoyanna',
        'තාක්ෂණ ශිල්පීන් සොයන්න',
    ],
    select_transformer_issues: [
        'select transformer issues',
        'transformer issues',
        'transformer getalu',
        'transformer problem',
        'ට්‍රාන්ස්ෆෝමර් ගැටළු',
        'ට්‍රාන්ස්ෆෝමර් පිපිරීම',
    ],
    select_power_line_faults: [
        'power line faults',
        'power line dosha',
        'විදුලි රේඛා දෝෂ',
    ],
    select_area_power_failure: [
        'area power failure',
        'pradeshiya widuli bindawateem',
        'ප්‍රදේශීය විදුලි බිඳවැටීම',
    ],
    select_substation_issues: [
        'substation issues',
        'upasthana getalu',
        'උපස්ථාන ගැටළු',
    ],
    select_complete_power_outage: [
        'complete power outage',
        'sampurna widuliya visandi weema',
        'සම්පූර්ණ විදුලිය විසන්ධි වීම',
    ],
    select_partial_power_outage: [
        'partial power outage',
        'ardha widuliya visandi weema',
        'අර්ධ විදුලිය විසන්ධි වීම',
    ],
    select_intermittent_supply: [
        'intermittent supply',
        'sthapitha nowana sepayuma',
        'ස්ථාපිත නොවන සැපයුම',
    ],
    select_scheduled_power_cut: [
        'scheduled power cut',
        'selasum kala widuli kappaduwa',
        'සැලසුම් කළ විදුලි කප්පාදුව',
    ],
    select_sudden_power_loss: [
        'sudden power loss',
        'hadisi widuli bindawateema',
        'හදිසි විදුලි බිඳවැටීම',
    ],
    select_low_voltage: [
        'low voltage',
        'adu voltage',
        'අඩු වෝල්ටීයතාවය',
    ],
    select_high_voltage: [
        'high voltage',
        'wadi voltage',
        'අධි වෝල්ටීයතාවය',
    ],
    select_fluctuating_voltage: [
        'fluctuating voltage',
        'asthawara voltage',
        'අස්ථාවර වෝල්ටීයතාවය',
    ],
    select_device_connectivity: [
        'device connectivity',
        'device sambandatha getalu',
        'උපාංග සම්බන්ධතා ගැටළුව',
    ],
};

const INTENT_TO_ACTION = {
    open_report_to_electricity_board: 'navigate_board_report',
    open_power_supply_issues: 'navigate_category',
    open_voltage_technical_issues: 'navigate_category',
    open_safety_related_issues: 'navigate_category',
    open_infrastructure_issues: 'navigate_category',
    open_monitoring_device_issues: 'navigate_category',
    open_activities: 'navigate_activities',
    view_activities: 'navigate_activities',
    open_account: 'navigate_account',
    open_profile_settings: 'navigate_profile_settings',
    open_help_support: 'navigate_help',
    open_about_us: 'navigate_about',
    change_language: 'toggle_language',
    go_home: 'go_home',
    go_back: 'go_back',
    select_transformer_issues: 'select_board_category',
    select_power_line_faults: 'select_board_category',
    select_weather_related_damage: 'select_board_category',
    select_pole_issues: 'select_board_category',
    select_short_circuit_or_fire: 'select_board_category',
    select_area_power_failure: 'select_board_category',
    select_substation_issues: 'select_board_category',
    select_meter_or_service_line_issues: 'select_board_category',
    select_external_or_human_causes: 'select_board_category',
    select_unknown_investigation_required: 'select_board_category',
    add_photo: 'add_photo',
    continue_next: 'continue',
    continue_to_location: 'continue',
    use_current_location: 'use_current_location',
    search_location: 'search_location',
    review_and_confirm_issue: 'confirm',
    confirm_location_and_report_issue: 'confirm',
    confirm_location_technician: 'confirm',
    find_available_technicians: 'confirm',
    submit_report: 'submit',
    select_complete_power_outage: 'select_service_issue',
    select_partial_power_outage: 'select_service_issue',
    select_intermittent_supply: 'select_service_issue',
    select_scheduled_power_cut: 'select_service_issue',
    select_sudden_power_loss: 'select_service_issue',
    select_low_voltage: 'select_service_issue',
    select_high_voltage: 'select_service_issue',
    select_fluctuating_voltage: 'select_service_issue',
    select_dim_lights: 'select_service_issue',
    select_sparks_from_meter: 'select_service_issue',
    select_burning_smell: 'select_service_issue',
    select_exposed_wiring: 'select_service_issue',
    select_electric_shock_risk: 'select_service_issue',
    select_damaged_power_lines: 'select_service_issue',
    select_fallen_pole: 'select_service_issue',
    select_broken_meter_box: 'select_service_issue',
    select_faulty_meter_reading: 'select_service_issue',
    select_smart_meter_issue: 'select_service_issue',
    select_device_connectivity: 'select_service_issue',
    open_jobs: 'navigate_jobs',
    open_history: 'navigate_history',
    open_earnings: 'navigate_earnings',
    open_service_setup: 'navigate_service_setup',
    open_chat: 'open_chat',
    track_technician: 'track_technician',
    make_payment: 'make_payment',
    rate_technician: 'rate_technician',
    accept_job: 'accept_job',
    view_job_details: 'view_job_details',
    cancel_request: 'cancel_job',
    cancel_dialog: 'cancel_dialog',
};

module.exports = {
    CATEGORY_INTENT_SAMPLES,
    INTENT_TO_ACTION,
};
